DROP TABLE IF EXISTS model;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS doctors;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS users_permissions;
DROP TABLE IF EXISTS permissions CASCADE;