###Create Doctor
POST localhost:8080/api/v1/doctors
Content-Type: application/json

{
  "firsName": "Beks",
  "lastName": "Zhaslan",
  "speciality": "dentist",
  "phone": "228336"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###Create User
POST localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Beks",
  "email": "beks@gmail.com",
  "phone": "pa55word"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Get Doctor with id=1
GET localhost:8080/api/v1/doctors/1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Sorted list of Patients
GET localhost:8080/api/v1/registrations/sorting?sort=id

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Filtered list of Patients
GET localhost:8080/api/v1/registrations?filter=Zh

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Paginated list of Patients
GET localhost:8080/api/v1/registrations/paginated?limit=3&offset=0

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Registration of the patient
PUT localhost:8080/api/v1/registrations/1
Content-Type: application/json

{
  "phone": "336228"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Delete Registration from Database
DELETE localhost:8080/api/v1/registrations/3
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}