###User Registration
POST localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Aidar",
  "email": "aidar@gmail.com",
  "password": "12345678"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###User Activation
PUT localhost:8080/api/v1/users/activated
Content-Type: application/json

{
  "token": "0B15996786302EA936C644D6DDD9D7B1DC1756FA4457C8A151DEFBF42C947948"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}




###Patients' APIs

###Create Registration of the Patient
POST localhost:8080/api/v1/creation
Content-Type: application/json

{
  "first_name": "Mohammed",
  "last_name": "Salah",
  "phone": "228336"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Get Patient with id=12
GET localhost:8080/api/v1/registrations/3

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Sorted list of Patients
GET localhost:8080/api/v1/registrations/sorting?sort=id

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Filtered list of Patients
GET localhost:8080/api/v1/registrations?filter=Zh

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Paginated list of Patients
GET localhost:8080/api/v1/registrations/paginated?limit=3&offset=0

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Registration of the patient
PUT localhost:8080/api/v1/registrations/1
Content-Type: application/json

{
  "phone": "336228"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Delete Registration from Database
DELETE localhost:8080/api/v1/registrations/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}%}