###Create Registration of the Patient
POST localhost:8080/api/v1/creation
Content-Type: application/json

{
  "name": "Aidar",
  "email": "aidar@gmail.com",
  "password": "1234"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}






###Patients API's

###Create Registration of the Patient
POST localhost:8080/api/v1/creation
Content-Type: application/json

{
  "first_name": "Mohammed",
  "last_name": "Salah",
  "phone": "228336"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Get Patient with id=1
GET localhost:8080/api/v1/registrations/3

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Sorted list of Patients
GET localhost:8080/api/v1/registrations/sorting?sort=id

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Filtered list of Patients
GET localhost:8080/api/v1/registrations?filter=Zh

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Paginated list of Patients
GET localhost:8080/api/v1/registrations/paginated?limit=3&offset=0

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Registration of the patient
PUT localhost:8080/api/v1/registrations/1
Content-Type: application/json

{
  "phone": "336228"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Delete Registration from Database
DELETE localhost:8080/api/v1/registrations/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}